language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - git clone git://github.com/maxmind/geoip-api-c
  - cd geoip-api-c
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
  - CFLAGS="-Werror -Wall -Wextra" python setup.py test

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
